### ISSUE TITLE
Runtime error: Connection failed in autograder and "port already in use" errors in command line

### ISSUE THREAD

**Issue by calebbg** [comp426-2022-fall/a01#10]
#### What is happening?
All of the autograder tests are failing and I'm getting errors when testing in the terminal. I am having trouble determining how to troubleshoot these issues.

#### What does the error say is happening?
A connection is failing to be established in the autograder, and in the command line there is a listen error because an address is already in use.

#### What do you think the error means?
I think it's either an issue with the way I am reading arguments or file, something in my listen function, or some combination of these.

#### Command string
node server.js
node server.js --port=5555

#### Code snippet
![image](https://user-images.githubusercontent.com/69723467/187921780-7b90d7c6-7d2b-4267-9e85-44aee6b7123b.png)
![image](https://user-images.githubusercontent.com/69723467/187955182-44a0af42-8da9-4cf5-952d-553d7ba8f37c.png)

#### Screenshots
![image](https://user-images.githubusercontent.com/69723467/187956486-21a80c35-e152-47e1-a7b8-801917a2f339.png)

#### Error log
calebbg@UNC-R90YDFXE:/mnt/c/Users/Caleb Gill/workspace/a01-calebbg$ node server.js --port=5555
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1432:16)
    at listenInCluster (node:net:1480:12)
    at Server.listen (node:net:1568:7)
    at /mnt/c/Users/Caleb Gill/workspace/a01-calebbg/server.js:50:10
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1459:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000

#### Node.js version
v16.17.0
#### Operating system
Linux UNC-R90YDFXE 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by camsimba** [comment]
Hey @calebbg,

I am going to add @jdmar3 to this, as my experience with the autograder and choosing ports is limited. At a glance, your code looks fine. It also looks like you tried changing the port to 5555, which is a great second try.

Let's see if John has some insight. @jdmar3

**Comment by unclily** [comment]
I am also having this similar issue. The only difference in my code is that I wrote:
const port = args.port || 3000

**Comment by VictorAriton** [comment]
@calebbg  Did you ever figure out the issue? I am having this error as well

**Comment by calebbg** [comment]
@jdmar3 https://github.com/comp426-2022-fall/a01-calebbg

**Comment by camsimba** [comment]
Hey @calebbg, if you are still having trouble I would recommend going to someone's office hours for help. The office hours are listed [here](https://github.com/comp426-2022-fall/syllabus/blob/main/officehours.md). The reason for this is that these issues are primarily meant to help facilitate visits to OH, with the easy ones being knocked out relatively quickly. If you are still having trouble after please let me know and we can dive a little further.

**Comment by jdmar3** [comment]
@camsimba He did go to office hours but they weren't able to figure it out. I told him to tag me. I'm looking into it.

**Comment by camsimba** [comment]
Gotcha, let me know if you need some help!

**Comment by jdmar3** [comment]
Okay I found the problems. I will outline them below.

Your code (lines 10-16) looks like this:

```
// Use minimist to process one argument `--port=` on the command line after `node server.js`.
const args = require('minimist')(process.argv.slice(2));
args["name"];

// Define a const `port` using the argument from the command line. 
// Make this const default to port 3000 if there is no argument given for `--port`.
const port = args.name || process.env.PORT || 3000;
```

You don't need line 12 at all, so just get rid of it.

In line 16 you are referring to `args.name`, which shouldn't exist at all. `args.port`, however, should.

To see what is in the `args` object, put the following somewhere:

```
console.log(args)
```

That will dump out into STDOUT the whole object that lives inside `args` that you created on line 11. Minimist is just creating an object by parsing the command line arguments (`processs.argv`) into options wherever it sees a hyphen or two hyphens for short and long options, respectively. So if you put `--port 5555` on the command line, minimist should turn that into something like `{"port": 5555}`, which means that you can refer to that variable inside whatever object you use to store the data that miminist parses, in this case `args`. This is why `args.port` should work and `args.name` should not. There is not command line argument for `--name`.

Other things that you might want to change:

In the instructions I mentioned loading `minimist` the same way that you loaded `fs`, so you can do that.

```
const minimist = require('minimist')
```

And then have a separate line that processes the `process.argv`, which is the command line arguments:

```
const args = minimist(process.argv.slice(2))
```

I hope that makes it clearer what minimist is actually doing here.

**Comment by calebbg** [comment]
That makes sense, and everything is working now. Thanks!
