### ISSUE TITLE
Clarification needed: What to do Exactly for fs Module AND Minimist

### ISSUE THREAD

**Issue by bdhack23** [comp426-2022-fall/a01#11]
I'm having a hard time understanding exactly what we need to do for the fs Module section of the assignment. In my code, I made sure to require the fs module. Then, I went straight to using the fs.readFile on ./public/index.html. I also included the "if" statement. Was this all we needed to do, or am I missing something? 
I am having similar issues with Minimist. I'm not sure if I'm doing things correctly. I made sure to require minimist, install it using npm, but after that I'm really confused on what order to do things for the port and creating the server. 

The instructions said that this would take only like 20 lines of code, but I feel like following all of the directions provided in the links would have us putting way more than that, so I'm assuming we do not follow the instructions of the links exactly. As in, we only do certain parts. I'm having a hard time figuring out which parts to follow.

**Comment by smelliskay** [comment]
Discussed in office hours. Student was confused partially about the order things happen in assignment 1, I provided her with the following information:

Require your modules -> Process your command line argument with minimist (don't forget to define allowed arg name) -> define your port -> read the file - > create your server and listen

These steps are more or less whats on the assignment instructions, but maybe it can be of help to someone to see it reworded.
