### ISSUE TITLE
Clarification needed: Defining a Port

### ISSUE THREAD

**Issue by bdhack23** [comp426-2022-fall/a01#13]
I'm failing the autograder and I'm thinking it has something to do with defining the port. I'm having difficulty figuring out what to do for it, I'm just not understanding how to apply the documentation to what we need to do. Are we supposed to do something like this?:
"const args = process.argv.slice(2);"
"node app.js brooke"
"node app.js port=brooke"

...(basically following the instructions step by step from the documentation)

Are we supposed to keep our name there? Are we somehow supposed to change up this code and make it apply to creating an argument for our port? If so, how? This is what the documentation did, so I would think it would be similar, but it's just not working. I'll attach some screenshots of the error messages from the autograder. Sorry if this post is a dumb question or if I'm overthinking the assignment.
<img width="495" alt="autograder_1" src="https://user-images.githubusercontent.com/77807845/188035644-9380a5a2-db44-42e2-a632-492962500eb1.PNG">
<img width="446" alt="autograder_2" src="https://user-images.githubusercontent.com/77807845/188035650-bd2f381c-f7f0-405f-bde0-7d6cfedbfef1.PNG">
<img width="443" alt="autograder_3" src="https://user-images.githubusercontent.com/77807845/188035656-a4ae0f6a-d0b2-48bb-bd9d-d2d1c584d68b.PNG">
<img width="437" alt="autograder_4" src="https://user-images.githubusercontent.com/77807845/188035665-86befb94-526a-4650-9459-0d4e4d7ac892.PNG">

**Comment by jessikka12** [comment]
Hi! let me try and help. 
`node` is a command that should be run in the terminal. You definitely don't want to put it in the code as it is not Javascript. 
As for how to get the value of the port, I would check out documentation at the bottom of a01, under the minimist module header.

**Comment by jessikka12** [comment]
Hi! let me try and help.
`node` is a command that should be run in the terminal. You definitely don't want to put it in the code as it is not Javascript.
As for how to get the value of the port, I would check out the link at the bottom of a01, under the minimist module header or google 'process.argv.slice(2)' for better documentation. This will help you create the `port` const that the assignment asks for. 

As an additional note, ports are identified by number so having `port=brooke` should default the port value to 3000 like the directions ask.

**Comment by bdhack23** [comment]
How would I run a node command within the vim file? I tried doing this:
typing ":"
then typing "node app.js port=brooke"
But that returned this error: E492: Not an editor command: node app.js port=brooke

So obviously that doesn't work.

**Comment by bdhack23** [comment]
Basically, I think my issue might be coming from this step in the instructions:
4. Use minimist to process one argument --port= on the command line after node server.js.

I'm not understanding how to use node server.js. So are we running this on a command line while inside the vim file? If so, how do we do this?? And yes, I've looked at the provided link, and it doesn't really tell me WHERE to put the node.js stuff.
