### ISSUE TITLE
Getting Error: Run server listening on randomly assigned port

### ISSUE THREAD

**Issue by bdhack23** [comp426-2022-fall/a01#14]
<img width="647" alt="screenshot_server_running" src="https://user-images.githubusercontent.com/77807845/188232125-31f318c1-90ee-4089-8207-94a41da9d11f.PNG">

What does this error mean exactly? I have 25000/50000 points in the autograder, so some of my assignment is correct.

**Comment by vennila-t** [comment]
I was also having trouble working on this in OH, we checked her port by using npm run and her server is running on port 5555 instead of 3000, can other LAs or @jdmar3 @camsimba take a look?

**Comment by Lamaab02** [comment]
I had a student with the same problem before and the issue was that they used '' instead of using `` when assigning the variable in {port},  so i suggest surrounding argument with the right annotations to indicate that that line has changeable variables!

**Comment by bdhack23** [comment]
@Lamaab02 I'm confused as to which line you are referring to. Are you talking about the const port line?

**Comment by Lamaab02** [comment]
in file server.js line 34 where u 
have $ {port}  the statement is surrounded by '' and it should take `` instead because ${port} is subject to change

**Comment by bdhack23** [comment]
@Lamaab02 Alright the score has definitely improved, but now it's just not passing the table check.
<img width="655" alt="autograder_5" src="https://user-images.githubusercontent.com/77807845/188942091-0d7f53ff-c35f-43a1-addc-0553a4154ba7.PNG">

**Comment by jdmar3** [comment]
You can put a link to that action run right in the issue and we can see it directly. It looks like the table doesn't have the correct information in it per the instructions.

**Comment by bdhack23** [comment]
@jdmar3 Oh wait I think I know how to fix this, thank you! haha!
