### ISSUE TITLE
Clarification needed: [Keeping receiving alter email from GitHub about workflow fall]

### ISSUE THREAD

**Issue by HuGuo-UNC-Chapel-Hill** [comp426-2022-fall/a01#2]
If there is something that seems off in the instructions , go through this checklist:

1. [ ] Is there an error in the text?
    - If yes, go to #2. 
    - If no, go to #3.
2. [ ] Did you create a pull request with a correction for the error?
    - If yes, then don't create an issue.
    - If no, then create a pull request with a suggested correction.
3. [ ] Did you read any documentation related to the thing that needs clarifying?
4. [ ] Did you Google the thing that needs clarifying?
5. [ ] Did you search or read through the other issues on this repo to make sure there isn't already a related issue?

None of the above, create an issue
------------------------------------------------------------------

Make sure to add **all the information needed to understand the error** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide URL of the file with the confusing thing.
- [ ] Identify the line number(s) in the file where the cunfusing thing is. 
- [ ] Describe what you find confusing?
- [ ] Take a guess and describe what you think the confusing thing might mean?

Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below. 

#### URL of file with confusing thing
![alt text](https://github.com/comp426-2022-fall/a00-onboarding-HuGuo-UNC-Chapel-Hill/blob/main/photo_2022-08-27_21-25-15.jpg?raw=true)

#### What is confusing?
When I followed the instruction to create node_modules, .package-lock.json, and index.html, I received three emails to alter my workflow failed.
I do not know if it is typical or if I did something wrong. Please give me some advice. Thank you very much.

**Comment by jdmar3** [comment]
Your code seems to be passing now, so I'm going to close this. https://github.com/comp426-2022-fall/a01-HuGuo-UNC-Chapel-Hill/actions/runs/2948737320
