### ISSUE TITLE
Clarification needed: [Adding HTML code to file]

### ISSUE THREAD

**Issue by Lesram21** [comp426-2022-fall/a01#4]
#### URL of file with confusing thing

https://classroom.github.com/a/d2j_Uokh

#### Line number of confusing thing

The section under "Make the public directory"

#### What is confusing?

I have already made the public directory and a file called index.html. The only thing I'm confused about it how to add the HTML code to the file. Am I supposed to use vim or a text editor (notepad) to complete this? Or am I going about this the wrong way?

#### What do you think the confusing thing means?

I think it means to add HTML code using a text editor, but I'm not entirely sure.

**Comment by jdmar3** [comment]
Yup just put the HTML in the file. Use VIM, ideally.
