### ISSUE TITLE
Runtime error: Error not printing out actual value of port to console. [Solution Found]

### ISSUE THREAD

**Issue by ZachCairns1** [comp426-2022-fall/a01#6]
If you are getting an error message, go through this checklist:

- [ ] Did you search or read through the other issues on this repo to make sure there isn't already a related issue?
- [ ] Have you read the words in the error message to understand their meaning?
- [ ] Have you Googled the words in the error message?
- [ ] Have you searched through the existing issues on this and other COMP 426 repositories to see if someone else identified and worked through the issue?

None of the above, create an issue
------------------------------------------------------------------

Make sure to add **all the information needed to understand the error** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Explain what you are trying to do and what is happening. 
- [ ] Provide the **_command string_** you are trying to run.
- [ ] Provide a **_code snippet_** if you are trying to run some code that you wrote. 
- [ ] Provide **_screenshots_** if applicable.
- [ ] Copy and paste the **_error log_** that shows up in the terminal.
- [ ] What is your **_Node.js version?_** (Run `node -v`.)
- [ ] What is your **_operating system?_** (Run `uname -a` and paste the output.)

Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below. 

#### What is happening?

The instruction says to print out "Server listening on port ${port}" to the console when the server is listening to the port, but when my local code ran this, it printed out literal string '${port}' everytime and not the intended port value. 

****This is fixed by instead of printing out `Server listening on port ${port}` to the console, I print out `Server listening on port ' + port. This prints out the actual port value

**Comment by camsimba** [comment]
Hey @ZachCairns1, glad you managed to fix the issue! I'll go ahead and close this, remember that you can close this manually if you find the answer. Let me know if you still need help on something!
