### ISSUE TITLE
 [Error: listen EADDRINUSE: address already in use :::3000] Mac-specific #1

### ISSUE THREAD

**Issue by emmagoodrich** [comp426-2022-fall/a01#7]
There was already an issue posted for this error, and the solution is to use a different port, but I have tried multiple other ports (such as 5555 and 8080 suggested in the other issue post) and I still get the same error. Were any Mac users able to find a port that works?

**Comment by camsimba** [comment]
Hey @emmagoodrich,

Could you please follow the issues format that John has posted? It helps us diagnose the issues faster when we have more information, such as screenshots and code snippets. Once you have posted them, we can help you more directly but without all the information from the issue format, we don't have much to go on. Thanks in advance!

**Comment by emmagoodrich** [comment]
> 

Yes, I will in the future, I only didn't this time because this same problem was addressed (in the proper format) already in a previous issue. I couldn't figure out a way to reopen or comment on that issue, so I only meant to reference it with this one, my apologies.
