### ISSUE TITLE
Runtime error: [BRIEF DESCRIPTION OF THE ERROR]

### ISSUE THREAD

**Issue by misaghh** [comp426-2022-fall/a01#8]
If you are getting an error message, go through this checklist:

- [ ] Did you search or read through the other issues on this repo to make sure there isn't already a related issue?
- was not sure if the question was answered, person was assigned to someone
- [ ] Have you read the words in the error message to understand their meaning?
- I have read it and is seem to not match the port listening 
- [ ] Have you Googled the words in the error message?
-  yes
- [ ] Have you searched through the existing issues on this and other COMP 426 repositories to see if someone else identified and worked through the issue?

None of the above, create an issue
------------------------------------------------------------------

Make sure to add **all the information needed to understand the error** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Explain what you are trying to do and what is happening. 
- I have followed the instruction and looked through the links provided to fix my issue or anything that seems off which i found some that were off but then still seem to not pass the autograder
- [ ] Provide the **_command string_** you are trying to run.
- [ ] Provide a **_code snippet_** if you are trying to run some code that you wrote. 
- [ ] Provide **_screenshots_** if applicable.
- [ ] Copy and paste the **_error log_** that shows up in the terminal.
- :error::The output for test Table check did not match%0AExpected:%0A<td>[Zz]<\/td>%0AActual:%0AServer listening on port 55899%0A./public/index.html
-::error::The output for test Content type did not match%0AExpected:%0AContent-Type: text\/html%0AActual:%0AServer listening on port 40544%0AHTTP/1.1 200 OK%0Acontent-type: text/html%0ADate: Wed, 31 Aug 2022 18:11:01 GMT%0AConnection: keep-alive%0AKeep-Alive: timeout=5
- [ ] What is your **_Node.js version?_** (Run `node -v`.) v16.17.0
- [ ] What is your **_operating system?_** (Run `uname -a` and paste the output.)
-  Darwin misaghs-mbp.wireless-1x.unc.edu 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64

Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below.

**Comment by camsimba** [comment]
Hey @misaghh, it looks like you solved this issue on your own, which is great! I am going to go ahead and close this.

In the future though, try and follow the format of an issue more closely. Instead of putting the information after the checklist that is meant for you to follow, put it under the bold headers below the checklist for clarity's sake.

Let me know if you still have some questions and we can reopen this!
