### ISSUE TITLE
Runtime error: curl: (3) URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by AdityaIyer01** [comp426-2022-fall/a01#9]
If you are getting an error message, go through this checklist:

- [ ] Did you search or read through the other issues on this repo to make sure there isn't already a related issue?
- [ ] Have you read the words in the error message to understand their meaning?
- [ ] Have you Googled the words in the error message?
- [ ] Have you searched through the existing issues on this and other COMP 426 repositories to see if someone else identified and worked through the issue?

None of the above, create an issue
------------------------------------------------------------------

Make sure to add **all the information needed to understand the error** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Explain what you are trying to do and what is happening. 
- [ ] Provide the **_command string_** you are trying to run.
- [ ] Provide a **_code snippet_** if you are trying to run some code that you wrote. 
- [ ] Provide **_screenshots_** if applicable.
- [ ] Copy and paste the **_error log_** that shows up in the terminal.
- [ ] What is your **_Node.js version?_** (Run `node -v`.)
- [ ] What is your **_operating system?_** (Run `uname -a` and paste the output.)

Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below. 

#### What is happening?
When I try to run the input from the first test locally, "PORT=\"$(shuf -i 2000-65535 -n 1)\"; (timeout --signal=SIGINT 5 node server.js --port=$PORT; exit 0) & sleep 1s && curl -vI http://localhost:${PORT} && sleep 5s", my program runs and prints out the html file. However, it also gives the following error: "curl: (3) URL using bad/illegal format or missing URL". I also fail this test on the github autograder.

#### What does the error say is happening?
My error states the following: "curl: (3) URL using bad/illegal format or missing URL"

#### What do you think the error means?
I am not sure what it means. It could be an issue with curl or the way I set up my environment.

#### Command string
PORT=\"$(shuf -i 2000-65535 -n 1)\"; (timeout --signal=SIGINT 5 node server.js --port=$PORT; exit 0) & sleep 1s && curl -vI http://localhost:${PORT} && sleep 5s

#### Code snippet
const http = require('http');
const fs = require('fs');
const args = require('minimist')(process.argv.slice(2));
const port = args.port || process.env.PORT || 3000;

var htmlOutput;
fs.readFile('./public/index.html', 'utf8', (err, data) => {
    if (err) {
        console.log(err);
        return;
    }
    console.log(data);
    htmlOutput = data;
});

const server = http.createServer((req, res) => {
    res.statusCode = 200;
    res.setHeader('Content-Type', 'text/html');
    res.end(htmlOutput);
})

server.listen(port, () => {
    console.log(`Server running at port ${port}`);
})

#### Error log
curl: (3) URL using bad/illegal format or missing URL

#### Node.js version
v16.17.0

#### Operating system
WSL Ubuntu

**Comment by camsimba** [comment]
Hi @AdityaIyer01, let me see if I can help some.

It looks like to me that what you are returning as part of the status log is incorrect, as the autograder is failing on the `Run server listening on randomly assigned port` test.
First, in your server.js file, line 52 of your code has the required output `Server listening on port ${port}`, but it looks like in line 55 you put `Server running at port ${port}`. While the differences are small, we require strict adherence to the instructions as small deviations later can have large issues. 
Second, it looks like you are printing to the console on line 34. This is going to automatically fail your test, as the autograder checks the output and filling it with your html is not expected. It would make sense if you were doing this for testing purposes, but for submission take this line out.

Try changing these and seeing if it works. If you still have issues, just let me know and we can dive more into them!

**Comment by camsimba** [comment]
Hey @AdityaIyer01, it looks like you managed to solve the issue so I am going to close it. If you still have any questions, feel free to reopen or comment on it!
